print("discussion about projects and example projects shown in the video ")
print("\nProject 1 : JARVIS ASSISTANT")
print("\nProject 2 : Love Calculator - randomly calculates love between two people given names")
print("\nProject 3 : Face Detection Software")
print("\nProject 4 : Flappy Bird Game")
print("\nProject 5 : Snake Game")
print("\n Download Python codes of above games , links given in video description")